version: '3'

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - minio

    volumes:
      - .:/app
    networks:
      - django_network

    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000 && python manage.py initialize_buckets"

  minio:
    image: minio/minio:latest
    volumes:
      - s3-volume:/data
    ports:
      - "9000:9000"
      - "9001:9001"

    expose:
      - "9000"
      - "9001"

    networks:
      - django_network

    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address :9001
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  create_buckets:
    image: minio/mc:latest
    depends_on:
      - minio

    networks:
      - django_network

    entrypoint: >
      /bin/sh -c '
      mc config host add s3 http://minio:9000 minio minio123 --api S3v4;
      [[ ! -z "`mc ls s3 | grep test`" ]] || mc mb s3/test;
      exit 0;
      '

volumes:
  s3-volume:

networks:
  django_network: