# Generated by Django 4.0.2 on 2022-02-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='file_url',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(default='d', upload_to=''),
            preserve_default=False,
        ),
    ]
