# Generated by Django 4.0.2 on 2022-02-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_uploadedfile_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='file',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='file_url',
            field=models.CharField(default='sd', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='type',
            field=models.CharField(max_length=4),
        ),
    ]
