# Generated by Django 4.0.2 on 2022-02-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_uploadedfile_file_uploadedfile_file_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='file_url',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(default='sd', upload_to='files/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='type',
            field=models.CharField(max_length=5),
        ),
    ]
